version: "3.9"
services:
  doe_pg:
    image: "postgres:12"
    container_name: "doe_postgres"
    restart: unless-stopped
    env_file:
      - Database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - doe-network
    ports:
      - 5432:5432
volumes:
    postgres:
networks:
  doe-network:
    driver: bridge
