version: "3"
services:
  frontend:
    container_name: "frontend"
    build:
      context: /home/devops/myagent/_work/3/s/
      dockerfile: Dockerfile
      args:
        - ServerUrl= ${ENV_API_URL}
    restart: unless-stopped
    networks:
      - doe-network
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - /home/devops/myagent/_work/3/s/certs:/etc/nginx/certs
  
  backend:
    depends_on:
      - doe_pg
    container_name: "backend"
    build:
      context: /home/devops/myagent/_work/1/s
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - doe-network
    expose:
      - "5000"
  doe_pg:
    image: "postgres:12"
    container_name: "doe_postgres"
    restart: unless-stopped
    env_file:
      - Database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - doe-network
    ports:
      - 5432:5432
volumes:
    postgres:
networks:
  doe-network:
    driver: bridge
