version: "3"
services:
  doe_frontend:
    container_name: "doe_frontend"
    build:
      context: /home/devops/myagent/_work/1/s/
      dockerfile: Dockerfile
      args:
        - ServerUrl= ${ENV_API_URL}
    restart: unless-stopped
    networks:
      - doe-network
    ports:
      - "80:80"
    env_file:
      - .env
  nginx:
    depends_on:
      - doe_backend
    container_name: "doe_nginx"
    build:
      context: /home/devops/myagent/_work/3/s/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - doe-network
    ports:
      - 1253:80
  doe_backend:
    depends_on:
      - doe_pg
    container_name: "doe_backend"
    build:
      context: /home/devops/myagent/_work/2/s/DOEAssessmentApp
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - doe-network
    ports:
      - "5000"
  doe_pg:
    image: "postgres:12"
    container_name: "doe_postgres"
    restart: unless-stopped
    env_file:
      - Database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - doe-network
    ports:
      - 5432:5432
volumes:
    postgres:
networks:
  doe-network:
    driver: bridge
